### ISSUE TITLE
unity throws errors

### ISSUE THREAD

**Issue by leftlinker** [invrpw/INVR-Platform-Exit-Function#1]
Assets\Scripts\Restart\ExitFunction.cs(45,31): error CS1069: The type name 'Point' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

Assets\Scripts\Restart\ExitFunction.cs(46,31): error CS1069: The type name 'Point' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

Assets\Scripts\Restart\ExitFunction.cs(47,31): error CS1069: The type name 'Rectangle' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

**Comment by MarieInvr** [comment]
Hey can you try removing the 3 lines (45-47)? 
In my tests it still works without them, so it should fix the error. If removing them works for you I would update the script for everyone, so please let me know :)

**Comment by robinnorth** [comment]
I've also encountered the same issues, to resolve you would need to add a reference to the `System.Drawing.dll` assembly in your Unity project. which can be done with the `csc.rsp` compiler options file that Unity supports (see https://docs.unity3d.com/Manual/PlatformDependentCompilation.html).

However, as the method that uses the struct in question:
https://github.com/invrpw/INVR-Platform-Exit-Function/blob/1f8b83b4a0a73037f90705e446bc90e0f3391966/ExitFunction.cs#L29
 is unused in the script, you could just remove that and the struct entirely.

**Comment by invrpw** [comment]
Update: Fix issue
